import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <head>

        {/* Using NextJS <Script> instead of <script> to avoid NextJS hydration issues */}
        {/* You may see this error on page load: 
        
        A tree hydrated but some attributes of the server rendered 
        HTML didn't match the client properties. This won't be patched up. 
        This can happen if a SSR-ed Client Component used. 
        This is caused by a Chrome Extension 
        you can ignore it as it does not cause issues with the functionality, 
        you may also open up the web page in incognito and the error will dissappear 
        */}

        <Script async src="https://www.googletagmanager.com/gtag/js?id=G-VW4LJV81L7" strategy="afterInteractive"/>

        <Script id="gtag-init" strategy="afterInteractive">
        {`
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments)}
        gtag('js', new Date());
        gtag('config', 'G-VW4LJV81L7');
        `}
        </Script>

      </head>


      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        {children}
      </body>
    </html>
  );
}
